# Generated by Django 4.0.6 on 2022-07-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0002_mento_post_like_count_profile_mento_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.PositiveIntegerField(default=36),
        ),
    ]
