# Generated by Django 4.0.6 on 2022-07-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(max_length=24, null=True, verbose_name='학교'),
        ),
    ]
